In [1]:
# <- This is a comment

In [9]:
# sum of a range of integers from 1 to n
# create a variable 
n = 5

print(n)

n

5


5

In [10]:
sum = 0
for x in range(1, n+1): #inclusive for the left value, exclusive for the right value
    print(x)
    sum = sum + x
print("sum", sum)    
print('sum', sum)

1
2
3
4
5
sum 15
sum 15


In [11]:
#if statements
if sum == 10:
    print("sum is 10!!!")
else:
    print("sum is not 10!!!")

sum is not 10!!!


In [12]:
# lists
list1 = [0,1,2,3,4,5]

In [14]:
print("fifth index", list1[0])

fifth index 0


In [16]:
print("4through 7", list1[0:3])

4through 7 [0, 1, 2]


In [17]:
print("Before", list1)

Before [0, 1, 2, 3, 4, 5]


In [18]:
list1.append(10)

In [19]:
print(list1)

[0, 1, 2, 3, 4, 5, 10]


In [21]:
sum = 0
for x in list1: 
    print(x)
    sum = sum + x
print("sum", sum)    

0
1
2
3
4
5
10
sum 25


In [22]:
import numpy as np

In [23]:
arr1 = np.array([1,2,3])
print(arr1)

[1 2 3]


In [27]:
arr2 = np.array([[4,5,6],[7,8,9]])
print(arr2)

[[4 5 6]
 [7 8 9]]


In [28]:
print(arr2[1][2])

9


In [33]:
arr3 = np.random.randint(1, 10, (2,3))  #(low, high-exclusive, (#rows,#cols))
print(arr3)

[[5 3 2]
 [5 2 5]]


In [34]:
np.median(arr3[0])

3.0

In [35]:
np.max(arr3)

5

In [37]:
np.sum(arr3[1])

12

In [39]:
print(arr1)
print(arr2)

[1 2 3]
[[4 5 6]
 [7 8 9]]


In [40]:
np.union1d(arr1,arr2)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr4 = np.array([5,6,7])
print(np.intersect1d(arr2,arr4))

[5 6 7]
